targets:
  $default:
    builders:
      reflect_gui_builder|reflectPresentationLibraryBuilder:
        generate_for:
          include:
          - lib/**.dart
        enabled: True
      reflect_gui_builder|reflectPresentationLibraryWriter:
        generate_for:
          - lib/**.dart
        enabled: True

builders:
  reflectPresentationLibraryBuilder:
    import: 'package:reflect_gui_builder/builder/builder_factory.dart'
    builder_factories: ['reflectPresentationLibraryBuilder']
    build_extensions:
      '.ignored1': # This is ignored. See ReflectPresentationLibraryBuilder.buildExtensions
        - '.ignored2' # This is ignored. See ReflectPresentationLibraryBuilder.buildExtensions
    auto_apply: root_package
    runs_before: [reflect_gui_builder|reflectPresentationLibraryWriter]
  reflectPresentationLibraryWriter:
    import: 'package:reflect_gui_builder/builder/builder_factory.dart'
    builder_factories: ['reflectPresentationLibraryWriter']
    build_extensions:
      '.ignored1': # This is ignored. See ReflectPresentationLibraryWriter.buildExtensions
        - '.ignored2'# This is ignored. See ReflectPresentationLibraryWriter.buildExtensions
    build_to: source
    auto_apply: root_package