name: reflect_gui_builder
description: Generates Reflect Graphical User Interface Code
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  source_gen: ^1.2.6
  build_runner: ^2.3.2
  collection: ^1.16.0
  analyzer: ^5.2.0
  dart_code: ^0.1.5
  fluent_regex: ^1.0.3
  recase: ^4.1.0
  logging: ^1.1.0
  yaml: ^3.1.1



dev_dependencies:
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/my_first_app.png