import 'package:reflect_gui_builder/builder/domain/service_class/service_class_presentation.dart'
    as i1;
import 'package:reflect_gui_builder/builder/domain/translation/translatable.dart'
    as i2;
import 'package:reflect_gui_builder/app/person/service/person_service.dart'
    as i3;
import 'package:reflect_gui_builder/builder/domain/action_method/action_method_presentation.dart'
    as i4;
import 'package:reflect_gui_builder/builder/domain/action_method_result_processor/action_method_result_processor.dart'
    as i5;
import 'package:reflect_gui_builder/builder/domain/action_method_parameter_processor/action_method_parameter_processor.dart'
    as i6;
import 'package:flutter/material.dart' as i7;

/// Do not make changes to this file!
/// This file is generated by: ReflectPresentationLibraryBuilder
/// On: 2023-01-08 16:32:45.445309
/// From: package:reflect_gui_builder/app/person/service/person_service.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
class $PersonServicePresentation extends i1.ServiceClassPresentation {
  @override
  final name = i2.Translatable(
      key:
          'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.name',
      englishText: 'People');
  @override
  final description = i2.Translatable(
      key:
          'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.description',
      englishText: 'People');
  @override
  final order = 100;
  @override
  final visible = true;
  @override
  final serviceObject = const i3.PersonService();
  final allCustomers = i4.ActionMethodPresentation(
      name: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.allCustomers.name',
          englishText: 'All customers'),
      description: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.allCustomers.description',
          englishText: 'All customers'),
      visible: true,
      order: 100,
      icon: const i5.ShowListInTableTab().defaultIcon ??
          const i6.ProcessResultDirectlyWhenThereIsNoParameter().defaultIcon ??
          i7.Icons.fiber_manual_record_rounded,
      parameterProcessor:
          const i6.ProcessResultDirectlyWhenThereIsNoParameter(),
      resultProcessor: const i5.ShowListInTableTab());
  final customersByGender = i4.ActionMethodPresentation(
      name: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.customersByGender.name',
          englishText: 'Customers by gender'),
      description: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.customersByGender.description',
          englishText: 'Customers by gender'),
      visible: true,
      order: 200,
      icon: const i5.ShowListInTableTab().defaultIcon ??
          const i6.EditEnumInDialog().defaultIcon ??
          i7.Icons.fiber_manual_record_rounded,
      parameterProcessor: const i6.EditEnumInDialog(),
      resultProcessor: const i5.ShowListInTableTab());
  @override
  List<i4.ActionMethodPresentation> get actionMethods =>
      [allCustomers, customersByGender];
}
