import 'package:reflect_gui_builder/builder/domain/service_class/service_class_presentation.dart'
    as i1;

/// Do not make changes to this file!
/// This file is generated by: ReflectGuiConfigBuilder
/// On: 2022-12-29 13:20:33.684248
/// From: package:reflect_gui_builder/app/person/service/person_service.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
class $PersonServicePresentation extends i1.ServiceClassPresentation {}
