import 'package:reflect_gui_builder/builder/domain/service_class/service_class_presentation2.dart'
    as i1;

/// Do not make changes to this file!
/// This file is generated by: ReflectPresentationLibraryBuilder
/// On: 2022-12-30 16:41:55.014292
/// From: package:reflect_gui_builder/app/person/service/person_service.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
class $PersonServicePresentation extends i1.ServiceClassPresentation {}
