import 'package:analyzer/file_system/overlay_file_system.dart';
import 'package:reflect_gui_builder/app/person/service/person_service.dart';
import 'package:reflect_gui_builder/builder/domain/service_class/service_class_presentation2.dart'
    as i1;
import 'package:reflect_gui_builder/builder/domain/translation/translatable.dart'
    as i2;
import 'package:reflect_gui_builder/builder/domain/action_method/action_method_presentation2.dart'
    as i3;

/// Do not make changes to this file!
/// This file is generated by: ReflectPresentationLibraryBuilder
/// On: 2023-01-02 17:49:41.277510
/// From: package:reflect_gui_builder/app/person/service/person_service.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
class $PersonServicePresentation extends i1.ServiceClassPresentation<PersonService> {
  @override
  final name = i2.Translatable(
      key:
          'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.name',
      englishText: 'People');
  @override
  final description = i2.Translatable(
      key:
          'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.description',
      englishText: 'People');
  @override
  final order = 100;
  @override
  final visible = true;


  final allCustomers = i3.ActionMethodPresentation(
      name: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.allCustomers.name',
          englishText: 'All customers'),
      description: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.allCustomers.description',
          englishText: 'All customers'),
      visible: true,
      order: 100,
      methodOwnerFactory: () => const ToDo());
  final customersByGender = i3.ActionMethodPresentation(
      name: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.customersByGender.name',
          englishText: 'Customers by gender'),
      description: i2.Translatable(
          key:
              'package:reflect_gui_builder/app/person/service/person_service.dart/PersonService.customersByGender.description',
          englishText: 'Customers by gender'),
      visible: true,
      order: 200,
      methodOwnerFactory: () => const ToDo());
  @override
  List<i3.ActionMethodPresentation> get actionMethods =>
      [allCustomers, customersByGender];
}
