import 'package:reflect_gui_builder/builder/domain/generic/documentation.dart';
import 'package:reflect_gui_builder/builder/reflect_presentation_library_builder.dart';

/// A [PresentationClass] is a Dart code class that is generated by
/// a [ReflectPresentationLibraryBuilder].
///
/// A [PresentationClass] :
/// * name ends with the Presentation suffix
///   e.g. PersonPresentation
/// * is created by a [PresentationClassFactory]
///   e.g. PersonPresentationFactory
/// * its generated code contains information that is used by the
///   graphical user interface.
class PresentationClass extends ConceptDocumentation {}

/// A [PresentationClassFactory]
/// * name ends with the PresentationFactory suffix
///   e.g. PersonPresentationFactory
/// * creates Dart code that implements a [PresentationClass] using a [SourceClass]
/// * is used by the [ReflectPresentationLibraryBuilder]
class PresentationClassFactory extends ConceptDocumentation {}
