import 'package:reflect_gui_builder/builder/domain/domain_class/domain_class_presentation.dart'
    as i1;
import 'package:reflect_gui_builder/builder/domain/domain_class/property/property_presentation.dart'
    as i2;

/// Do not make changes to this file!
/// This file is generated by: ReflectPresentationLibraryBuilder
/// On: 2023-01-08 12:18:09.344671
/// From: package:reflect_gui_builder/app/person/domain/person.dart
/// Generate command: dart run build_runner build --delete-conflicting-outputs
/// For more information see: TODO
class $PersonPresentation extends i1.DomainClassPresentation {
  var name=PropertyPresentation(name: name, description: description, visible: visible, order: order, type: type, widgetFactory: widgetFactory);
  var gender;
  var id;
  var eMailAddresses;
  @override
  List<i2.PropertyPresentation> get properties =>
      [name, gender, id, eMailAddresses];
}
